version: '3.8'

services:
  web:
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 --reload project.asgi:application"

  celery:
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    command: celery -A project worker --loglevel=debug --reload
