# Generated by Django 4.2.24 on 2025-09-25 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("xmlFeedPath", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="frames/")),
                ("coordinates", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutputImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100)),
                ("product_image_url", models.URLField()),
                ("image", models.ImageField(upload_to="output_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="app.frame",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["frame", "product_id"],
                        name="app_outputi_frame_i_43b71c_idx",
                    ),
                    models.Index(
                        fields=["frame", "-created_at"],
                        name="app_outputi_frame_i_eafc8d_idx",
                    ),
                ],
                "unique_together": {("frame", "product_id")},
            },
        ),
        migrations.AddIndex(
            model_name="frame",
            index=models.Index(
                fields=["owner", "-created_at"], name="app_frame_owner_i_d4054d_idx"
            ),
        ),
    ]
